---
- name: install Apache
  apt:
    name: apache2
    state: present
  tags: apache 

- name: Copy homepage
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  when: env == 'staging'
  tags: apache

- name: Start and enable Apache
  service:
    name: apache2
    state: started
    enabled: yes
  tags: apache
