---
- hosts: webservers
  become: true
  vars_files:
    - group_vars/all/vault.yml
  tasks:
    - name: Ping webservers
      ping:
    - name: Install curl
      apt:
        name: curl
        state: present
  roles: 
    - webserver
